### !pip install joblib

In [15]:
import os 
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pandas as pd

plt.style.use("fivethirtyeight")

In [45]:
class Perceptron:
        def __init__(self, eta: float=None, epochs: int=None):
            self.weights = np.random.randn(3) * 1e-4
            self.eta = eta # learning rate
            self.epochs = epochs # iterations

        def _z_outcome(self, inputs, weights):
            return np.dot(inputs, weights)

        def activation_function(self, z):
            return np.where(z > 0, 1, 0)

        def fit(self, X, y):
            self.X = X
            self.y = y

            X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
            print(f"X with bias: \n{X_with_bias}")

            for epoch in range(self.epochs):
                print("--"*10)
                print(f"for epoch >> {epoch + 1}")
                print("--"*10)

                z = self._z_outcome(X_with_bias, self.weights)
                y_hat = self.activation_function(z)
                print(f"predicted value after forward pass: \n{y_hat}")

                self.error = self.y - y_hat
                print(f"error: \n{self.error}")

                self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
                print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
                print(f"##"*10)
    
        def predict(self, X):
            X_with_bias = np.c_[X, -np.ones((len(X), 1))]
            z = self._z_outcome(X_with_bias, self.weights)
            return self.activation_function(z)

In [16]:
OR={
    "x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,1,1,1]    
}
df_OR = pd.DataFrame(OR)

df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [17]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X, y

In [20]:
X, y = prepare_data(df_OR)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [46]:
X, y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA, epochs=EPOCHS)

model_or.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 2.05416449e-05 -6.46003783e-05  9.99308302e-02]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.20002054  0.1999354  -0.20006917]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 0.20002054  0.1999354  -0.10006917]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Na

In [47]:
model_or.predict(X=[[0,0]])

array([0])

In [48]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
}

df_AND = pd.DataFrame(AND)

df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [50]:
X,y=prepare_data(df_AND)
Eta=0.1
epochs=10
model_AND = Perceptron(eta=Eta, epochs=epochs)

model_AND.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.1000231   0.10005268 -0.09987521]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[2.31034850e-05 5.26775449e-05 2.00124791e-01]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[0.1000231  0.10005268 0.10012479]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y,

In [51]:
XOR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)

df_XOR

X, y = prepare_data(df_XOR)

ETA = 0.1
EPOCHS = 10

model_xor = Perceptron(eta=ETA, epochs=EPOCHS)

model_xor.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[1 1 0 0]
error: 
0   -1
1    0
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 9.97465608e-02 -1.54395844e-05 -3.81950241e-05]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[-0.00025344 -0.10001544  0.1999618 ]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 9.97465608e-02 -1.54395844e-05 -3.81950241e-05]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2   